/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeCode_MemBarrier */

#ifndef _Included_nativeCode_MemBarrier
#define _Included_nativeCode_MemBarrier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeCode_MemBarrier
 * Method:    flushAllThreads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativeCode_MemBarrier_flushAllThreads
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
